business_listing/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.apiOverview, name="api-overview"),

	############ based on function 
	# path('task-list/', views.taskList, name="task-list"),
	# path('task-detail/<str:pk>/', views.taskDetail, name="task-detail"),
	# path('task-create/', views.taskCreate, name="task-create"),

	# path('task-update/<str:pk>/', views.taskUpdate, name="task-update"),
	# path('task-delete/<str:pk>/', views.taskDelete, name="task-delete"),

	########## Based on class
	path('task-list/', views.taskList.as_view(), name="task-list"),
	path('task-detail/<int:id>/', views.taskDetail.as_view(), name="task-detail"),
	
	# path('task-create/', views.taskCreate, name="task-create"),

	# path('task-update/<str:pk>/', views.taskUpdate, name="task-update"),
	# path('task-delete/<str:pk>/', views.taskDelete, name="task-delete"),
]

business_listing/backend/urls.py
from django.urls import path
from backend.views import *
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    
    path('getGrowerList/', GrowerListView.as_view()),

    path('testoauth', TemplateView.as_view(template_name="account/login11.html")),
    path('', index, name='admin_index'),
    path('login/', loginUser, name='login'),
    path('login_action/', login_action, name='login_action'),
    path('logout/', logoutUser, name='logout'),

    # t have state and city list based on country
    path('get_state_list/', get_state_list, name='get_state_list'),
    path('get_city_list/', get_city_list, name='get_city_list'),

    #-------------- based on form --------------------#
    path('registerpage/', registerPage, name='registerpage'),
    path('updateprofile/<str:uuid_code>/', updateProfile, name='updateprofile'),
    path('change_password/', change_password, name='change_password'),

    ############# forgot password and reset password ----###########################
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"), 
        name="password_reset_complete"),

    ###################################### Forgot and Reset Password done #############


    # Agent section 
    path('agentlist/', agentList, name='agentList'),
    path('getvendorlist/<str:uuid_code>', getVendorList, name='getvendorlist'),
    path('delete-vendor/<str:uuid_code>', deleteVendor, name='delete-vendor'),

    # now Agent can add vendor to his vendor list
    path('addvendor/', addVendor, name='addvendor'),
    # Indivudual vendor list who are not under any agent
    path('individual_vendor_list/', individual_vendor_list, name='individual_vendor_list'),

    ########### Parlour section ############
    path('list-parlour/', list_parlour, name='list-parlour'),
    path('add-parlour/', add_parlour, name='add-parlour'),
    path('edit-parlour/<str:uuid_code>/', edit_parlour, name='edit-parlour'),
    path('delete-parlour/<str:uuid_code>/', delete_parlour, name='delete-parlour'),
    path('change_status/', change_status, name='change_status'),

    ########### Parlour service section ############
    path('list-parlour-service/<str:uuid_code>/', list_parlour_service, name='list-parlour-service'),
    path('add-parlour-service/', add_parlour_service, name='add-parlour-service'),
    path('edit-parlour-service/<str:uuid_code>/', edit_parlour_service, name='edit-parlour-service'),
    path('delete-parlour-service/<str:uuid_code>/', delete_parlour_service, name='delete-parlour-service'),
    path('change_status_parlour_service/', change_status_parlour_service, name='change_status_parlour_service'),
    

    # TO UPLOAD AND DISPALY BOOK
    path('books/', book_list, name='book_list'),
    path('books/upload/', upload_book, name='upload_book'),
    path('books/update_book/<int:id>/', update_book, name='update_book'),
    path('books/delete_book/<int:id>/', delete_book, name='delete_book'),



    #-------------------------------------------------#

    path('admin_profile/', admin_profile, name='admin_profile'),
    path('admin_profile_edit/', admin_profile_edit, name='admin_profile_edit'),
    path('admin_password_view/', admin_password_view, name='admin_password_view'),
    path('admin_password_update/', admin_password_update, name='admin_password_update'),
    path('admin_email_view/', admin_email_view, name='admin_email_view'),
    path('admin_email_update/', admin_email_update, name='admin_email_update'),

]

business_listing/business_listing/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backadmin/', include('backend.urls')),
    # path('', include('frontend.urls')),
    path('accounts/', include('allauth.urls')),
    # set path to redirect after google login

    # for restframework api
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

business_listing/backend/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

class MyUser(AbstractUser):
    # user_type_id => 1-> Admin 2-> Agent 3-> Vendor 4-> Customer
    user_type_id = models.IntegerField(null=True)
    is_individual_vendor = models.IntegerField(default=0)
    phone_number = models.CharField(max_length=255, null=True)
    created_date = models.DateField(auto_now_add = True, null=True)
    modified_date = models.DateField( null=True)

    uuid_code = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    
    
class MyUserProfile(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE, null=True)
    
    country = models.IntegerField(null=True)
    state = models.IntegerField(null=True)
    city = models.IntegerField(null=True)
    landmark = models.CharField(max_length=255,null=True)
    address = models.CharField(max_length=255,null=True)
    # address = models.TextField(null=True)
    pincode = models.CharField(max_length=255,null=True)
    picture = models.ImageField(upload_to='profile/', null=True, blank=True)
    created_date = models.DateField(auto_now_add = True, null=True)
    modified_date = models.DateField( null=True)

    def __str__(self):
        return self.user.first_name

class VendorList(models.Model):
    agent = models.ForeignKey(MyUser, on_delete=models.CASCADE, null=True)    
    vendor_id = models.IntegerField(null=True)

# customed Model Manager
class ParlourManager(models.Manager):
    def check_phonenumber(self, phone_number):
        if len(phone_number) == 10:
            return 'phone_number is correct'

        else:
            return 'Please check phone number'

class ParlourQuerySet(models.QuerySet):
    def check_phonenumber(self, phone_number):
        if len(phone_number) == 10:
            return 'phone_number is correct'

        else:
            return 'Please check phone number'          

# Create your models here.
class Parlour(models.Model):
    vendor = models.ForeignKey(MyUser,related_name='vendor', on_delete=models.CASCADE, null=True)
    agent = models.ForeignKey(MyUser, related_name='agent',on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, null=True)
    phone_number = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=255, null=True)
    landmark = models.CharField(max_length=255,null=True)
    country = models.IntegerField(null=True)
    state = models.IntegerField(null=True)
    city = models.IntegerField(null=True)
    pincode = models.CharField(max_length=255,null=True)
    picture = models.ImageField(upload_to='parlour/profile/', null=True, blank=True)

    status = models.CharField(max_length=10, default='active')
    created_date = models.DateField(auto_now_add = True, null=True)
    created_by = models.IntegerField(null=True)
    modified_date = models.DateField(null=True)
    modified_by = models.IntegerField(null=True)

    uuid_code = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)

    # objects = ParlourManager()
    parman = ParlourQuerySet()

      
    def __str__(self):
        return self.name

class ParlourService(models.Model):
    parlour = models.ForeignKey(Parlour,related_name='parlour', on_delete=models.CASCADE, null=True)
    service_name = models.CharField(max_length=255, null=True)
    service_duration= models.CharField(max_length=255, null=True)
    service_price = models.FloatField(default=0.0, null=True)
    service_material= models.TextField(null=True)

    status = models.CharField(max_length=10, default='active')
    created_date = models.DateField(auto_now_add = True, null=True)
    modified_date = models.DateField(null=True)

    uuid_code = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)


    # def __init__(self):
    #      super(Paid, self).__init__()
    #      self.uuid_code = str(uuid.uuid4())

    # this needs to be corrected
    def get_absolute_url(self):
        return "/path/%s/" %(self.uuid_code)

    def __str__(self):
        return self.service_name

# to recieive email from business owners
class adminEmail(models.Model):
    receive_email = models.CharField(max_length=255)
    from_email = models.CharField(max_length=255)       

    def __str__(self):
        return self.from_email

class VendorInfo(models.Model):
    myuser = models.ForeignKey(MyUser, on_delete=models.CASCADE, null=True)
    info = models.TextField(null=True)
    service = models.TextField(null=True)

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    # for file uploading  
    pdf = models.FileField(upload_to='Books/pdf/') 
    # for image uploading  
    cover = models.ImageField(upload_to='Books/cover/', null=True, blank=True)     

    def __str__(self):
        return self.from_email

class Countries(models.Model):
    country_id = models.IntegerField(null=True)
    sortname = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=250, null=True)
    phonecode = models.IntegerField(null=True)

    objects = models.Manager() # read docs


class States(models.Model):
    state_id = models.IntegerField(null=True)
    name = models.CharField(max_length=255, null=True)
    country_id = models.IntegerField(null=True)

    objects = models.Manager() # read docs

class Cities(models.Model):
    city_id = models.IntegerField(null=True)
    name = models.CharField(max_length=255, null=True)
    state_id = models.IntegerField(null=True)

    objects = models.Manager() # read docs

business_listing/backend/views/agents.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from datetime import datetime
from django.http import JsonResponse, HttpResponse
from django.conf import settings

# Create your views here.
from backend.serializers import *
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from rest_framework import mixins
from backend.models import *
from backend.decorators import *
from backend.forms import *
import os, sys

@login_required()
def agentList(request):
    agents= MyUser.objects.filter(user_type_id=2)
    return render(request,'agent/agent_list.html',{'agents':agents,'agentlist_active':'active'})

@login_required()
def getVendorList(request, uuid_code):
    print('Agent with uuid_code : ',uuid_code)
    user_id = MyUser.objects.get(uuid_code=uuid_code)
    vendorlistUderThisAgent = VendorList.objects.filter(agent_id=user_id).values_list('vendor_id',flat=True) 
    print('vendorlistUderThisAgent: ',vendorlistUderThisAgent)

    vendorList= MyUser.objects.filter(id__in = vendorlistUderThisAgent)
    return render(request,'agent/vendor_list.html',{'vendorList':vendorList,'agentlist_active':'active'})

@login_required()
def addVendor(request):
    print('When adding vendorAgent with id : ',request.user.id)
    
    # user = MyUser.objects.get(id=pk)
    # myProfile = MyUserProfile.objects.get(user=user)
    if request.method == 'POST':
        userform = UpdateUserForm(request.POST,request.FILES)#, instance=user)
        userProfileForm = UpdateUserProfileForm(request.POST,request.FILES) #,instance=myProfile)
        if userform.is_valid() and userProfileForm.is_valid():
            user = userform.save(commit=False)
            user.user_type_id = 3
            user.save()
            userProfile = userProfileForm.save(commit=False)
            userProfile.user_id = user.id
            userProfile.modified_date = datetime.now()
            userProfile.save()

            # make a vendorlist based on agent
            obj = VendorList(vendor_id=user.id, agent_id = request.user.id)
            obj.save()
            return redirect('admin_index')
        else:
        	print('error in vendor add form')
        	for i in userform.errors:
        		print(i)

    userform = UpdateUserForm()
    profileform = UpdateUserProfileForm()
    context = {'form':userform,'profileform':profileform,'addvendor_active':'active'}
    return render(request, 'edit_profile_using_form.html', context)

@login_required()
def individual_vendor_list(request):
	# ------------ dont need calculation as we have added a field for is_individual_vendor ----#
	# # now find all vendors whose user_type_id = 3
	# allVendors = MyUser.objects.filter(user_type_id=3).values_list('id', flat=True).order_by('id')
	# allVendors = [i for i in allVendors]
	# print('allVendors :',allVendors)
	# #now find all vendors who are under any agents
	# allVendorsUnderAgents = VendorList.objects.all().values_list('vendor_id', flat=True).order_by('id')
	# allVendorsUnderAgents = [i for i in allVendorsUnderAgents]
	# print('allVendorsUnderAgents :',allVendorsUnderAgents)
	# individual_vendors = [x for x in allVendors if x not in allVendorsUnderAgents]
	# print('individual_vendors :',individual_vendors)

	vendorList= MyUser.objects.filter(is_individual_vendor = 1, user_type_id=3)
	return render(request,'agent/vendor_list.html',{'vendorList':vendorList,'vendorlist':'active'})

@login_required()
def deleteVendor(request, uuid_code):
    vendor_obj= MyUser.objects.get(uuid_code = uuid_code)
    # remove stored image from system
    # remove_old_image_from_system(vendor_obj.picture)
    vendor_obj.delete()
    return redirect('getvendorlist', uuid_code=request.user.uuid_code)

business_listing/backend/views/common.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from datetime import datetime
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from backend.models import *
from backend.decorators import *

#set global; variables to access at some other files
selected_parlour_id = None
selected_parlour_uuid_code = None

def get_state_list(request):
    country_id = request.POST['country_id']
    state_obj_list = States.objects.filter(country_id=country_id)
    state_dict = {}
    for state in state_obj_list:
        state_dict[str(state.state_id)] = state.name
    return JsonResponse(state_dict)

def get_city_list(request):
    state_id = request.POST['state_id']
    cities_obj_list = Cities.objects.filter(state_id=state_id)
    city_dict = {}
    for city in cities_obj_list:
        city_dict[str(city.city_id)] = city.name
    return JsonResponse(city_dict)

business_listing/backend/templates/parlour/list_parlour.html
{% load static %}
{% include 'common/admin_header.html' %}
{% include 'common/admin_leftmenu.html' %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Parlour List</h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'admin_index' %}"><i class="fa fa-dashboard" aria-hidden="true"></i>Dashboad</a></li>
            <li class="active">Parlour List</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 table-responsive">
                <div class="box">
                    <div class="box-header">
                       <!--  <h3 class="box-title">Slider List</h3> -->
                    </div>
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        <a class="close" href="#" data-dismiss="alert">×</a>
                        {{ message }}
                    </div>
                    {% endfor %}
                    <div class="col-md-12" style="">
                    
                    <a href="{% url 'add-parlour' %}" class="btn btn-info btn-sm"><i class="fa fa-plus" aria-hidden="true"></i> Add New Parlour</a>
                       
                    <button  class="btn btn-sm btn-success" onclick="change_status('active')"><i class="fa fa-check" aria-hidden="true"></i> Active</button>
                    <button  class="btn btn-sm btn-danger" onclick="change_status('inactive')"><i class="fa fa-times" aria-hidden="true"></i> Inactive</button>

                   
                    </div>
                    <div class="clearfix"></div>
                    <!-- /.box-header -->
                    <div class="box-body about_booking">
                        <table id="example1" class="table table-bordered table-hover table-condensed table-responsive">
                            <thead>
                            <tr class="bg-blue">
                            <th><input type="checkbox" id="checkAll" name="checkAll"></th>
                            <th>Status</th>
                            <th>Parlour Name</th>
                            <th>Phone Number</th>
                            <th>Parlour Address</th>
                            <th>Parlour Services</th>
                            <th>Owner</th>
                            <th>Agent</th>
                            <th>Joining Date</th>
                            <th>Parlour Image</th>
                            <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                              {% for parlour in parlour_list %}
                                <tr>
                                 <td><input type="checkbox" id="check" name="check" value="{{ parlour.id }}"></td>
                                    <td>
                                        {% if parlour.status == 'active' %} 
                                            <img src="{% static 'image/active.png' %}" class="img-responsive" >
                                        {% else %}
                                             <img src="{% static 'image/inactive.png' %}" class="img-responsive">
                                        {% endif %}
                                    </td>
                                    <td>{{ parlour.name }}</td>
                                    <td>{{ parlour.phone_number }}</td>
                                    <td>{{ parlour.address }}</td>

                                    <td class="last_th">
                                        <a href="{% url 'list-parlour-service' parlour.uuid_code %}" class="btn-primary btn-sm" title="Edit"><i class="fa fa-list" aria-hidden="true"></i></a>
                                        
                                    </td>
                                    
                                    <td>{{ parlour.vendor }}</td>
                                    <td>{{ parlour.agent }}</td>
                                    <td>{{ parlour.created_date }}</td>

        
                                    
                                    <td>
                                        {% if parlour.picture %}
                                        <img src="{{ parlour.picture.url }}" width="150" height="64">
                                        
                                        {% else %}
                                             <img src="{% static 'image/no-image.jpg' %}" class="img-responsive" width="150" height="64">

                                        {% endif %}
                                    </td>

                                    <td class="last_th">
                                        <a href="{% url 'edit-parlour' parlour.uuid_code %}" class="btn-primary btn-sm" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                        <a href="{% url 'delete-parlour' parlour.uuid_code %}" class="btn-danger btn-sm" name="" id="" onclick="return confirm('Are you sure ?')" title="delete"><i class="fa fa-trash" aria-hidden="true"></i></a>

                                    
                                </tr>
                              {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>


<script>
    $("#checkAll").change(function () {
        $("input:checkbox").prop('checked', $(this).prop("checked"));
    });

    function change_status(status)
    {
        var favorite = [];
        $.each($("input[name='check']:checked"), function(){
            favorite.push($(this).val());
        });

        var value=favorite;
        if(value=="")
        {
            alert('Please select atleast one record');
        }
        else
        {
            $.ajax({
                    type: "POST",
                    url:"{% url 'change_status' %}",
                    data: {id:value,status:status, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: "json",
                    async: false,
                    success: function(data)
                    {
                        if(data.result==1)
                        {
                            alert('Status Changed Successfully');
                            location.reload();
                        }
                    }
                });
        }

    }

</script>

{% include 'common/admin_footer.html' %}